CREATE DATABASE CAPSTONE;

USE CAPSTONE;

CREATE TABLE ROLE (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  NAME TEXT NOT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE USER (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(50) NOT NULL,
  USERNAME VARCHAR(50) NOT NULL,
  EMAIL VARCHAR(50) NOT NULL,
  PASSWORD TEXT(100) NOT NULL,
  PHONE TEXT(15) NOT NULL,
  ADDRESS TEXT,
  JOIN_DATE TIMESTAMP,
  PHOTO TEXT,
  LATITUDE DECIMAL(10, 8),
  LONGITUDE DECIMAL(11, 8),
  IS_ACTIVE BIT(1),
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE USER_ROLE (
  USER_ID BIGINT(20) NOT NULL,
  ROLE_ID BIGINT(20) NOT NULL,
  PRIMARY KEY (USER_ID, ROLE_ID),
  CONSTRAINT FK_USER FOREIGN KEY (USER_ID) REFERENCES USER(ID),
  CONSTRAINT FK_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


INSERT INTO ROLE(NAME) VALUES('ROLE_ADMIN');
INSERT INTO ROLE(NAME) VALUES('ROLE_PM');
INSERT INTO ROLE(NAME) VALUES('ROLE_FARMER');
INSERT INTO ROLE(NAME) VALUES('ROLE_BUYER');
INSERT INTO ROLE(NAME) VALUES('ROLE_DRIVER');

INSERT INTO USER(NAME, USERNAME, EMAIL, PASSWORD, PHONE, ADDRESS, JOIN_DATE, PHOTO, LATITUDE, LONGITUDE, IS_ACTIVE) VALUES('admin', 'admin', 'admin@gmail.com', '$2a$10$j9LW3hic3F5s1soqsRqgX.jbCA631SmxI.tdyhS0SUPeoglbpHihK', '0123456789', '', now(), '', null, null,  1);
INSERT INTO USER_ROLE(USER_ID, ROLE_ID) VALUES(1, 1);

CREATE TABLE FARM (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  ADDRESS TEXT,
  IMAGES TEXT,
  LATITUDE DECIMAL(10, 8) NOT NULL,
  LONGITUDE DECIMAL(11, 8) NOT NULL,
  USER_ID BIGINT(20) NOT NULL,

  PRIMARY KEY (ID),
  FOREIGN KEY (USER_ID) REFERENCES USER(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE VEHICLE (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  NAME TEXT NOT NULL,
  PHOTO TEXT,
  PRICE_PER_KM BIGINT(20) NOT NULL,
  WEIGHT_CARRY BIGINT(20) NOT NULL,
  USER_ID BIGINT(20) NOT NULL,

  PRIMARY KEY (ID),
  FOREIGN KEY (USER_ID) REFERENCES USER(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE PRODUCT (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  NAME TEXT NOT NULL,
  CATEGORY TEXT NOT NULL,
  PRICE BIGINT(20) NOT NULL,
  PROMOTION_PRICE BIGINT(20) NOT NULL,
  PROMOTION_ACTIVE BIT(1) NOT NULL,
  DESCRIPTION TEXT NOT NULL,
  IMAGES TEXT NOT NULL,
  DATE_CREATED TIMESTAMP NOT NULL,
  LATITUDE DECIMAL(10, 8) NOT NULL,
  LONGITUDE DECIMAL(11, 8) NOT NULL,
  USER_ID BIGINT(20) NOT NULL,

  PRIMARY KEY (ID),
  FOREIGN KEY (USER_ID) REFERENCES USER(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE COMMENT (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  CONTENT TEXT NOT NULL,
  DATE_CREATED TIMESTAMP NOT NULL,
  COMMENTED_BY BIGINT(20) NOT NULL,
  PRODUCT_ID BIGINT(20) NOT NULL,

  PRIMARY KEY (ID),
  FOREIGN KEY (COMMENTED_BY) REFERENCES USER(ID),
  FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE SUBCOMMENT (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  CONTENT TEXT NOT NULL,
  DATE_CREATED TIMESTAMP NOT NULL,
  COMMENTED_BY BIGINT(20) NOT NULL,
  COMMENT_ID BIGINT(20) NOT NULL,

  PRIMARY KEY (ID),
  FOREIGN KEY (COMMENTED_BY) REFERENCES USER(ID),
  FOREIGN KEY (COMMENT_ID) REFERENCES COMMENT(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE RATE (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  STAR INT NOT NULL,
  DATE_CREATED TIMESTAMP NOT NULL,
  RATED_BY BIGINT(20) NOT NULL,
  PRODUCT_ID BIGINT(20) NOT NULL,

  PRIMARY KEY (ID),
  FOREIGN KEY (RATED_BY) REFERENCES USER(ID),
  FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE CHAT (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  CONTENT TEXT NOT NULL,
  DATE_CREATED TIMESTAMP NOT NULL,
  FROM_USER BIGINT(20) NOT NULL,
  TO_USER BIGINT(20) NOT NULL,
  SOURCE_VISIBLE BIT(1),
  DESTINATION_VISIBLE BIT(1),

  PRIMARY KEY (ID),
  FOREIGN KEY (FROM_USER) REFERENCES USER(ID),
  FOREIGN KEY (TO_USER) REFERENCES USER(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE DISH (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  NAME TEXT NOT NULL,
  PRICE BIGINT(20) NOT NULL,
  DESCRIPTION TEXT NOT NULL,
  IMAGES TEXT NOT NULL,
  DATE_CREATED TIMESTAMP NOT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE ORDERING (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  ORDER_ID TEXT NOT NULL,
  DATE TIMESTAMP NOT NULL,
  ORDER_BY BIGINT(20) NOT NULL,
  ADDRESS TEXT NOT NULL,
  LATITUDE DECIMAL(10, 8) NOT NULL,
  LONGITUDE DECIMAL(11, 8) NOT NULL,
  TOTAL_PRICE BIGINT(20) NOT NULL,
  STATUS TEXT NOT NULL,

  PRIMARY KEY (ID),
  FOREIGN KEY (ORDER_BY) REFERENCES USER(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE ORDERITEM (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  PRODUCT_ID BIGINT(20) NOT NULL,
  QUANTITY BIGINT(20) NOT NULL,
  ORDER_ID BIGINT(20) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID),
  FOREIGN KEY (ORDER_ID) REFERENCES ORDERING(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;