CREATE DATABASE CAPSTONE;

USE CAPSTONE;

CREATE TABLE ROLE (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  NAME TEXT NOT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE USER (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(50) NOT NULL,
  USERNAME VARCHAR(50) NOT NULL,
  EMAIL VARCHAR(50) NOT NULL,
  PASSWORD TEXT(100) NOT NULL,
  PHONE TEXT(15) NOT NULL,
  ADDRESS TEXT,
  JOIN_DATE TIMESTAMP,
  PHOTO TEXT,
  LATITUDE DECIMAL(10, 8),
  LONGITUDE DECIMAL(11, 8),
  IS_ACTIVE BIT(1),
  MESSAGES TEXT,

  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE USER_ROLE (
  USER_ID BIGINT(20) NOT NULL,
  ROLE_ID BIGINT(20) NOT NULL,
  PRIMARY KEY (USER_ID, ROLE_ID),
  CONSTRAINT FK_USER FOREIGN KEY (USER_ID) REFERENCES USER(ID),
  CONSTRAINT FK_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


INSERT INTO ROLE(NAME) VALUES('ROLE_ADMIN');
INSERT INTO ROLE(NAME) VALUES('ROLE_PM');
INSERT INTO ROLE(NAME) VALUES('ROLE_FARMER');
INSERT INTO ROLE(NAME) VALUES('ROLE_BUYER');
INSERT INTO ROLE(NAME) VALUES('ROLE_DRIVER');

INSERT INTO USER(NAME, USERNAME, EMAIL, PASSWORD, PHONE, ADDRESS, JOIN_DATE, PHOTO, LATITUDE, LONGITUDE, IS_ACTIVE) VALUES('admin', 'admin', 'admin@gmail.com', '$2a$10$j9LW3hic3F5s1soqsRqgX.jbCA631SmxI.tdyhS0SUPeoglbpHihK', '0123456789', '', now(), '', null, null,  1);
INSERT INTO USER_ROLE(USER_ID, ROLE_ID) VALUES(1, 1);

CREATE TABLE FARM (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  ADDRESS TEXT,
  IMAGES TEXT,
  LATITUDE DECIMAL(10, 8) NOT NULL,
  LONGITUDE DECIMAL(11, 8) NOT NULL,
  USER_ID BIGINT(20) NOT NULL,

  PRIMARY KEY (ID),
  FOREIGN KEY (USER_ID) REFERENCES USER(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE VEHICLE (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  NAME TEXT NOT NULL,
  PHOTO TEXT,
  PRICE_PER_KM BIGINT(20) NOT NULL,
  WEIGHT_CARRY BIGINT(20) NOT NULL,
  USER_ID BIGINT(20) NOT NULL,

  PRIMARY KEY (ID),
  FOREIGN KEY (USER_ID) REFERENCES USER(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE PRODUCT (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  NAME TEXT NOT NULL,
  CATEGORY TEXT NOT NULL,
  PRICE BIGINT(20) NOT NULL,
  PROMOTION_PRICE BIGINT(20) NOT NULL,
  PROMOTION_ACTIVE BIT(1) NOT NULL,
  DESCRIPTION TEXT NOT NULL,
  IMAGES TEXT NOT NULL,
  DATE_CREATED TIMESTAMP NOT NULL,
  LATITUDE DECIMAL(10, 8) NOT NULL,
  LONGITUDE DECIMAL(11, 8) NOT NULL,
  USER_ID BIGINT(20) NOT NULL,

  PRIMARY KEY (ID),
  FOREIGN KEY (USER_ID) REFERENCES USER(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE COMMENT (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  CONTENT TEXT NOT NULL,
  DATE_CREATED TIMESTAMP NOT NULL,
  COMMENTED_BY BIGINT(20) NOT NULL,
  PRODUCT_ID BIGINT(20) NOT NULL,

  PRIMARY KEY (ID),
  FOREIGN KEY (COMMENTED_BY) REFERENCES USER(ID),
  FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE SUBCOMMENT (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  CONTENT TEXT NOT NULL,
  DATE_CREATED TIMESTAMP NOT NULL,
  COMMENTED_BY BIGINT(20) NOT NULL,
  COMMENT_ID BIGINT(20) NOT NULL,

  PRIMARY KEY (ID),
  FOREIGN KEY (COMMENTED_BY) REFERENCES USER(ID),
  FOREIGN KEY (COMMENT_ID) REFERENCES COMMENT(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE RATE (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  STAR INT NOT NULL,
  DATE_CREATED TIMESTAMP NOT NULL,
  RATED_BY BIGINT(20) NOT NULL,
  PRODUCT_ID BIGINT(20) NOT NULL,

  PRIMARY KEY (ID),
  FOREIGN KEY (RATED_BY) REFERENCES USER(ID),
  FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE CHAT (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  CONTENT TEXT NOT NULL,
  DATE_CREATED TIMESTAMP NOT NULL,
  FROM_USER BIGINT(20) NOT NULL,
  TO_USER BIGINT(20) NOT NULL,
  SOURCE_VISIBLE BIT(1),
  DESTINATION_VISIBLE BIT(1),
  SEEN BIT(1),

  PRIMARY KEY (ID),
  FOREIGN KEY (FROM_USER) REFERENCES USER(ID),
  FOREIGN KEY (TO_USER) REFERENCES USER(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE ORDERING (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  ORDER_ID TEXT NOT NULL,
  DATE TIMESTAMP NOT NULL,
  ORDER_BY BIGINT(20) NOT NULL,
  ADDRESS TEXT NOT NULL,
  LATITUDE DECIMAL(10, 8) NOT NULL,
  LONGITUDE DECIMAL(11, 8) NOT NULL,
  TOTAL_PRICE BIGINT(20) NOT NULL,
  STATUS TEXT NOT NULL,

  PRIMARY KEY (ID),
  FOREIGN KEY (ORDER_BY) REFERENCES USER(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE ORDERITEM (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  PRODUCT_ID BIGINT(20) NOT NULL,
  QUANTITY BIGINT(20) NOT NULL,
  ORDER_ID BIGINT(20) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID),
  FOREIGN KEY (ORDER_ID) REFERENCES ORDERING(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE STATE (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  NAME TEXT NOT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE USER ADD MESSAGES TEXT;

ALTER TABLE ORDERING ADD SHIPPING_METHOD TEXT;
ALTER TABLE ORDERING ADD SHIPPING_PRICE BIGINT(20);

ALTER TABLE PRODUCT ADD QUANTITY BIGINT(20);
ALTER TABLE PRODUCT ADD STORE_LOCATION BIT(1);
ALTER TABLE PRODUCT ADD LOCATION_REF BIGINT(20);

ALTER TABLE ORDERITEM ADD PRICE BIGINT(20);

ALTER TABLE USER ADD STATE TEXT;

ALTER TABLE FARM ADD STATE TEXT;



-- Insert state
INSERT INTO STATE(NAME) VALUES('Metro Manila');
INSERT INTO STATE(NAME) VALUES('Abra');
INSERT INTO STATE(NAME) VALUES('Agusan del Norte');
INSERT INTO STATE(NAME) VALUES('Agusan del Sur');
INSERT INTO STATE(NAME) VALUES('Aklan');
INSERT INTO STATE(NAME) VALUES('Albay');
INSERT INTO STATE(NAME) VALUES('Antique');
INSERT INTO STATE(NAME) VALUES('Apayao');
INSERT INTO STATE(NAME) VALUES('Aurora');
INSERT INTO STATE(NAME) VALUES('Bataan');
INSERT INTO STATE(NAME) VALUES('Basilan');
INSERT INTO STATE(NAME) VALUES('Benguet');
INSERT INTO STATE(NAME) VALUES('Biliran');
INSERT INTO STATE(NAME) VALUES('Bohol');
INSERT INTO STATE(NAME) VALUES('Batangas');
INSERT INTO STATE(NAME) VALUES('Batanes');
INSERT INTO STATE(NAME) VALUES('Bukidnon');
INSERT INTO STATE(NAME) VALUES('Bulacan');
INSERT INTO STATE(NAME) VALUES('Cagayan');
INSERT INTO STATE(NAME) VALUES('Camiguin');
INSERT INTO STATE(NAME) VALUES('Camarines Norte');
INSERT INTO STATE(NAME) VALUES('Capiz');
INSERT INTO STATE(NAME) VALUES('Camarines Sur');
INSERT INTO STATE(NAME) VALUES('Catanduanes');
INSERT INTO STATE(NAME) VALUES('Cavite');
INSERT INTO STATE(NAME) VALUES('Cebu');
INSERT INTO STATE(NAME) VALUES('Compostela Valley');
INSERT INTO STATE(NAME) VALUES('Davao Oriental');
INSERT INTO STATE(NAME) VALUES('Davao Occidental');
INSERT INTO STATE(NAME) VALUES('Davao del Sur');
INSERT INTO STATE(NAME) VALUES('Davao del Norte');
INSERT INTO STATE(NAME) VALUES('Dinagat Islands');
INSERT INTO STATE(NAME) VALUES('Eastern Samar');
INSERT INTO STATE(NAME) VALUES('Guimaras');
INSERT INTO STATE(NAME) VALUES('Ifugao');
INSERT INTO STATE(NAME) VALUES('Iloilo');
INSERT INTO STATE(NAME) VALUES('Ilocos Norte');
INSERT INTO STATE(NAME) VALUES('Ilocos Sur');
INSERT INTO STATE(NAME) VALUES('Isabela');
INSERT INTO STATE(NAME) VALUES('Kalinga');
INSERT INTO STATE(NAME) VALUES('Laguna');
INSERT INTO STATE(NAME) VALUES('Lanao del Sur');
INSERT INTO STATE(NAME) VALUES('Leyte');
INSERT INTO STATE(NAME) VALUES('La Union');
INSERT INTO STATE(NAME) VALUES('Marinduque');
INSERT INTO STATE(NAME) VALUES('Maguindanao');
INSERT INTO STATE(NAME) VALUES('Masbate');
INSERT INTO STATE(NAME) VALUES('Occidental Mindoro');
INSERT INTO STATE(NAME) VALUES('Oriental Mindoro');
INSERT INTO STATE(NAME) VALUES('Mountain Province');
INSERT INTO STATE(NAME) VALUES('Misamis Occidental');
INSERT INTO STATE(NAME) VALUES('Misamis Oriental');
INSERT INTO STATE(NAME) VALUES('Cotabato');
INSERT INTO STATE(NAME) VALUES('Negros Occidental');
INSERT INTO STATE(NAME) VALUES('Negros Oriental');
INSERT INTO STATE(NAME) VALUES('Northern Samar');
INSERT INTO STATE(NAME) VALUES('Nueva Ecija');
INSERT INTO STATE(NAME) VALUES('Nueva Vizcaya');
INSERT INTO STATE(NAME) VALUES('Pampanga');
INSERT INTO STATE(NAME) VALUES('Pangasinan');
INSERT INTO STATE(NAME) VALUES('Palawan');
INSERT INTO STATE(NAME) VALUES('Quezon');
INSERT INTO STATE(NAME) VALUES('Quirino');
INSERT INTO STATE(NAME) VALUES('Rizal');
INSERT INTO STATE(NAME) VALUES('Romblon');
INSERT INTO STATE(NAME) VALUES('Sarangani');
INSERT INTO STATE(NAME) VALUES('South Cotabato');
INSERT INTO STATE(NAME) VALUES('Siquijor');
INSERT INTO STATE(NAME) VALUES('Southern Leyte');
INSERT INTO STATE(NAME) VALUES('Sulu');
INSERT INTO STATE(NAME) VALUES('Sorsogon');
INSERT INTO STATE(NAME) VALUES('Sultan Kudarat');
INSERT INTO STATE(NAME) VALUES('Surigao del Norte');
INSERT INTO STATE(NAME) VALUES('Surigao del Sur');
INSERT INTO STATE(NAME) VALUES('Tarlac');
INSERT INTO STATE(NAME) VALUES('Tawi-Tawi');
INSERT INTO STATE(NAME) VALUES('Samar');
INSERT INTO STATE(NAME) VALUES('Zamboanga del Norte');
INSERT INTO STATE(NAME) VALUES('Zamboanga del Sur');
INSERT INTO STATE(NAME) VALUES('Zambales');
INSERT INTO STATE(NAME) VALUES('Zamboanga City');
INSERT INTO STATE(NAME) VALUES('Zamboanga Sibugay');